services:
  scoreboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - scoreboard-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    networks:
      - scoreboard-network

networks:
  scoreboard-network:
